# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.City')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=100)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('description', models.TextField()),
                ('image_list', models.ImageField(blank=True, null=True, upload_to='vacancy_pictures')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Company')),
            ],
        ),
    ]
