# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.City'),
        ),
    ]
