# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_auto_20180210_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ends_at',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.ManyToManyField(to='recruiting.City'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='starts_at',
            field=models.CharField(max_length=20),
        ),
    ]
