# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_auto_20180210_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='vacancy_pictures')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='image_list',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image_list',
            field=models.ManyToManyField(to='recruiting.ImageFile'),
        ),
    ]
