# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_auto_20180210_2314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFile',
            new_name='VacancyImage',
        ),
    ]
