# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_auto_20180210_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'vacancies'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.ManyToManyField(related_name='locations', to='recruiting.City'),
        ),
    ]
