# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_auto_20180211_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.ManyToManyField(to='recruiting.City'),
        ),
    ]
