# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_auto_20180211_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyimage',
            name='file',
        ),
        migrations.AddField(
            model_name='vacancyimage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
