# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0008_auto_20180211_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyimage',
            old_name='file_url',
            new_name='url',
        ),
    ]
